modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/TakeruDavis/CreateCardboardedConveynience/issues"

[[mods]]
modId = "cardboarded_conveynience"
version = "${version}"
displayName = "Create: Cardboarded Conveynience"
logoFile = "assets/cardboarded_conveynience/icon.png"
authors = "TakeruDavis"
description = '''
A small tweak allowing players to be disguised as packages even on chain conveyor. Extra chain conveyor related features may come in the future.
'''

[[dependencies.cardboarded_conveynience]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cardboarded_conveynience]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cardboarded_conveynience]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cardboarded_conveynience]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "NONE"
side = "BOTH"
